import { defineJoinerConfig, Modules } from "@srinivasulu-narayanam/framework/utils"

export const joinerConfig = defineJoinerConfig(Modules.API_KEY, {
  linkableKeys: {
    // Merged with the autogenerated ones to maintain backward compatibility
    publishable_key_id: "ApiKey",
  },
})
